In [9]:
import os
import sys

import matplotlib.pyplot as plt
import numpy as np
import proplot as pplt
from ipywidgets import interact
from ipywidgets import widgets

sys.path.append("/home/46h/repo/psdist/")
import psdist as ps
import psdist.visualization as psv

In [10]:
pplt.rc["cycle"] = "538"
pplt.rc["cmap.discrete"] = False
pplt.rc["cmap.sequential"] = "viridis"
pplt.rc["figure.facecolor"] = "white"
pplt.rc["grid"] = False

In [1]:
eigenvectors = np.array([
    [1.25171349e+00-2.08810289j, 1.25171349e+00-2.08810289j, 2.57931125e+00+0.j, 2.57931125e+00+0.j],
    [-1.92772499e-01-0.07949326j, -1.92772499e-01-0.07949326j, -8.04834747e-04-0.19306255j, -8.04834747e-04-0.19306255j],
    [-2.58312739e+00-0.j, -2.58312739e+00-0.j, 1.07231715e+00+2.09119227j, 1.07231715e+00+2.09119227j],
    [5.74049321e-03+0.19277733j, 5.74049321e-03+0.19277733j, 1.89714695e-01-0.09820014j, 1.89714695e-01-0.09820014j]
])

In [3]:
v1, _, v2, _ = eigenvectors.T

In [25]:
np.conj(eigenvectors[:, 0])

array([ 1.25171349+2.08810289j, -0.1927725 +0.07949326j,
       -2.58312739-0.j        ,  0.00574049-0.19277733j])

In [30]:
eigenvectors[:, 0]

array([ 1.25171349-2.08810289j, -0.1927725 -0.07949326j,
       -2.58312739+0.j        ,  0.00574049+0.19277733j])

In [31]:
eigenvectors[:, 2]

array([ 2.57931125e+00+0.j        , -8.04834747e-04-0.19306255j,
        1.07231715e+00+2.09119227j,  1.89714695e-01-0.09820014j])

In [47]:
J1 = 0.00
J2 = 10.00
psi1 = np.radians(0.0)
psi2 = np.radians(0.0)

X = []
for psi2 in np.linspace(0.0, 2.0 * np.pi, 100):
    x1 = np.exp(-1.0j * psi1) * np.sqrt(2.0 * J1) * v1
    x2 = np.exp(-1.0j * psi2) * np.sqrt(2.0 * J2) * v2
    x = np.real(x1 + x2)
    X.append(x)
X = np.array(X)

In [48]:
@interact()
def update(i=(0, X.shape[0] - 1)):
    grid = psv.CornerGrid(d=4, diag=False, labels=["x", "xp", "y", "yp"])
    grid.plot_cloud(X, kind="scatter")
    grid.plot_cloud(X[i : i + 1, :], kind="scatter", color="red", s=12)

interactive(children=(IntSlider(value=49, description='i', max=99), Output()), _dom_classes=('widget-interact'…

In [50]:
np.max(np.abs(X), axis=0)

array([11.53503058,  0.8633504 , 10.50896271,  0.95535134])